frr version 9.1
frr defaults traditional
hostname r2
log stdout
!
interface lo
 ip address 10.0.0.2/32
!
router ospf
 ospf router-id 10.0.0.2
 network 10.0.0.2/32 area 0
 network 10.0.12.0/29 area 0
 redistribute bgp
!
router bgp 65002
 no bgp ebgp-requires-policy
 neighbor 10.0.23.3 remote-as 65003
 !
 address-family ipv4 unicast
  redistribute ospf
  neighbor 10.0.23.3 activate
 exit-address-family
!
line vty
!
